<!-- Example single danger button -->
<div class="btn-group">
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    New Cars
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="https://scrappage.co.uk/sp/car-marques/marque/mercedes/">Mercedes-Benz</a>
    <a class="dropdown-item" href="https://scrappage.co.uk/sp/car-marques/marque/ford/">Ford</a>
  </div>
</div>