<?php
declare(strict_types=1);

if(empty($this->modeldata)) {
    echo "No Model Data Found";
    return;
}

$modeldata              = $this->modeldata;
$spxmodel_Model         = '';
$spxmodel_Marque        = '';
$spxmodel_ModelDetail   = '';

$extractc = extract($modeldata,EXTR_PREFIX_ALL | EXTR_OVERWRITE, 'spxmodel');

$marqueKeyName  = array_flip($this->marquemap)[$spxmodel_Marque];
$marqueUrl      = $this->serverUrl($this->url('carmarques',['marque' => $marqueKeyName]));
$marqueLink     =<<<EOF
    <a href="$marqueUrl">$spxmodel_Marque</a>
EOF;

$carmodelsUrl = $this->serverurl(
    $this->url(
        'carmodels',
        [
            'marque' => $spxmodel_Marque,
            'model' => $spxmodel_Model
        ]
    )
);

$modelLink=<<<EOF
<a href="$carmodelsUrl">$spxmodel_Model</a>
EOF;

//TODO - should be Marque Model Submodel(consisting of various fields depending
//on distinguishing fields availability e.g. engine, submodel, transmission)
 $this->headTitle("$spxmodel_Marque $spxmodel_Model $spxmodel_ModelDetail");

$headerline =<<<EOF
<div class="carheader">$marqueLink $modelLink $spxmodel_ModelDetail</div>
EOF;

$excludes           = ['Marque','Model'];
$cardatalines       = '';
$price_indicative   = 0;

foreach ($modeldata as $field => $val) {

    switch($field) {

        case '_id':
        break;

        case (in_array($field, $excludes)):
        break;

        default:

        $cardatalines .=<<<EOF
        <div class="cardataline">
            $field
        </div>
        <div class="cardataline">
            $val
        </div>
EOF;





        if (strpos($field, 'price_i_') !== false  ) {
            $val = (float) $val;
            $spxmodel_dispprice = money_format('%.2n', $val);
            $price_indicative = $val;
        }
    }
}

$modeldata = '';

$cargrid =<<<EOF
<div class="cargrid">
EOF;

    $cargrid .= $headerline;
    $cargrid .= $cardatalines;
    $cargrid .=<<<EOF
</div>
EOF;

    $ident = 'thiscar';
$paraident = 'par-'.$ident;
$priceident = 'price-'.$ident;
$scrappageident = 'scrappage-'.$ident;
$deposit = 5000;

//TODO - scrappage discount must be accessible via API
//Or provide estimate based on price/marque/type etc.
$scrappagediscount = 2000;

$hpform =<<<EOF
<div id="$paraident" class="$ident marker quotegrid">
    <div class="quotegridfieldheader">
        HP Quote Estimate        
    </div>
    
    <div class="quotegridtext">
        <b><i>STEP 1.</i></b> Adjust inputs as necessary, monthly payments will update instantly.
            For example if you think you can get a zero interest rate deal enter 0 in the Interest Rate field
            or if your purchase price is different adjust the price field.
    </div>    
    
    <div class="quotegridfield">Price(£)........</div>
    <div class="quotegridvalue"><input type="text" class="quoteinput price priceinput $paraident" value="$price_indicative" autocomplete="off"></div>
    
    <div class="quotegridfield">Deposit(£)........</div>
    <div class="quotegridvalue"><input type="text" class="quoteinput spxinput deposit $paraident" value="$deposit" autocomplete="off"></div>
    
    <div class="quotegridfield">Scrappage/Trade-In (£)........</div>
    <div class="quotegridvalue"><input type="text" class="quoteinput spxinput scrappagedisc $paraident" value="$scrappagediscount"></div>

    <div class="quotegridfield">Amount to finance........</div>
    <div class="quotegridvalue"> <span class="quotedisplay financeamount $paraident">0</span></div>

    <div class="quotegridfield">No. monthly payments........</div>
    <div class="quotegridvalue"><input type="text" class="quoteinput spxinput numpayments $paraident" value="48" ></div>

    <div class="quotegridfield">Interest Rate(%)........</div>
    <div class="quotegridvalue"><input type="text" class="quoteinput spxinput interestrate $paraident" value="5.9"></div>
    
    <div class="quotegridfield">Est. Monthly Payment(£).....</div>
    <div class="quotegridvalue"><span style="color:green; font-weight:bold; font-size:xx-large" class="quotedisplay monthlypayment $paraident">0</span></div>    

    <div class="quotegridtext">
       <b><i>STEP 2.</i></b> Get it financed at <a href="https://www.paidonresults.net/c/49722/1/1819/0" style="font-size:x-large">Car Finance Deals</a> 
    </div>

        
</div>
EOF;

$cont=<<<EOF
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            $cargrid
        </div>
        <div class="col-md-4">
            $hpform
        </div>
    </div>
</div>
EOF;

echo $cont;

