<?php
declare(strict_types=1);

if(empty($this->modeldata)) {
    echo "No Model Data Found";
    return;
}

$modeldata              = $this->modeldata;
$spxmodel_Model         = '';
$spxmodel_Marque        = '';
$spxmodel_ModelDetail   = '';

$extractc = extract($modeldata,EXTR_PREFIX_ALL | EXTR_OVERWRITE, 'spxmodel');

$marqueKeyName  = array_flip($this->marquemap)[$spxmodel_Marque];
$marqueUrl      = $this->serverUrl($this->url('carmarques',['marque' => $marqueKeyName]));
$marqueLink     =<<<EOF
    <a href="$marqueUrl">$spxmodel_Marque</a>
EOF;

$carmodelsUrl = $this->serverurl(
    $this->url(
        'carmodels',
        [
            'marque' => $spxmodel_Marque,
            'model' => $spxmodel_Model
        ]
    )
);

$modelLink=<<<EOF
<a href="$carmodelsUrl">$spxmodel_Model</a>
EOF;

//TODO - should be Marque Model Submodel(consisting of various fields depending
//on distinguishing fields availability e.g. engine, submodel, transmission)
 $this->headTitle("$spxmodel_Marque $spxmodel_Model $spxmodel_ModelDetail");

$headerline =<<<EOF
<div class="carheader">$marqueLink $modelLink $spxmodel_ModelDetail</div>
EOF;

$excludes           = ['Marque','Model'];
$cardatalines       = '';
$price_indicative   = 0;

foreach ($modeldata as $field => $val) {

    switch($field) {

        case '_id':
        break;

        case (in_array($field, $excludes)):
        break;

        default:

        $cardatalines .=<<<EOF
        <div class="cardataline">
            $field
        </div>
        <div class="cardataline">
            $val
        </div>
EOF;





        if (strpos($field, 'price_i_') !== false  ) {
            $val = (float) $val;
            $spxmodel_dispprice = money_format('%.2n', $val);
            $price_indicative = $val;
        }
    }
}

$modeldata = '';

$cargrid =<<<EOF
<div class="cargrid">
EOF;

    $cargrid .= $headerline;
    $cargrid .= $cardatalines;
    $cargrid .=<<<EOF
</div>
EOF;

    $ident = 'thiscar';
$paraident = 'par-'.$ident;
$priceident = 'price-'.$ident;
$scrappageident = 'scrappage-'.$ident;
$deposit = 5000;

//TODO - scrappage discount must be accessible via API
//Or provide estimate based on price/marque/type etc.
$scrappagediscount = 2000;

$data['price_indicative'] = $price_indicative;
$data['deposit'] = $deposit;
$data['scrappagediscount'] = $scrappagediscount;

$hpform = $this->HpQuoteHelper($data);


$cont=<<<EOF
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            $cargrid
        </div>
        <div class="col-md-4">
            $hpform
        </div>
    </div>
</div>
EOF;

echo $cont;

