<?php
declare(strict_types=1);
$this->headTitle('Car Finance'); ?>
<h2 class="entry-title">Car Finance</h2>


<div class="entry-content">
    <p>Car Finance exists because most car buyers want to access cars where the purchase price is higher than the amount they can afford to pay, or would like to pay, up front.</p>
    <p>By using finance car buyers can obtain cars avoiding the high up-front cost of an immediate full payment.</p>
    <p>Vehicle finance is provided by vehicle finance companies, sometimes owned by the manufacturer. They are offered to dealers at a buy rate. The dealers may then offer their customer the loan at a higher rate at a profit to the dealer. These deals can be offered in conjunction with Scrappage offers where the dealer agrees to pay a fixed sum for you trade-in vehicle.</p>
    <p>Car financing is available in different ways — the most popular being PCP (Personal Contract Plan), Hire Purchase and straight forward car loans.</p>
    <p>Most new cars are purchased using some form of finance — FLA (Finance &amp; Leasing Association) members provided finance to over 86% of private car sales in 2016. Some 82% of these were purchased through the highly popular PCP financing. The rest being made up from HP and then standard car loans.</p>
    <h3>Choosing between HP &amp; PCP</h3>
    <p>If you want low monthly payments and/or not sure what you want to do at the end of the finance period choose PCP. Read More on PCP finance examples and where to get PCP deals.</p>
    <p>If you know you will want to keep the car at the end of the loan term then <a href="https://scrappage.co.uk/sp/hire-purchase-hp/">HP</a> may be for you — it will be a lower overall cost if you keep the car. Read More on <a href="https://scrappage.co.uk/sp/hire-purchase-hp/">HP finance</a> examples and where to get HP deals.</p>
</div>