<?php
declare(strict_types=1);

$itemdata = $this->itemdata;

if ($this->itemdata['_total_items'] !== 1) {
    echo "No Car Data Found or Error has occurred.";
    return;
}

$dispe = '';
$displayForm = '';

if (isset($this->edititemform)) {

    $this->edititemform->prepare();
    $this->edititemform->setAttribute('method', 'post');
    $this->edititemform->setAttribute('id','addcar');

    $displayForm = $this->form()->openTag($this->edititemform);

    /** @var \Zend\Form\Element $element */
    foreach ($this->edititemform->getElements() as $name => $element) :

        if (!empty($element->getAttributes()['type'])) {
            switch ($element->getAttributes()['type']) {

                case 'submit':
                    $element->setAttributes(['class' => 'btn btn-default']);
                    $displaySubmitButton = $this->formElement($element);
                    break;

                case 'hidden':
                    $displayForm .= $this->formElement($element);
                    break;

                default:
                    $element->setAttributes(['class' => 'form-control']);
                    $displayForm
                        .= <<<EOF
            <div class = "form-group">
EOF;
                    if (!empty($element->getLabel())) {
                        $displayForm .= $this->formLabel($element);
                    }
                    $displayForm .= $this->formElement($element);
                    $displayForm .= $this->formElementErrors($element);
                    $displayForm .= '</div>';
                    break;
            }
        }
        elseif ($name == 'g-recaptcha-response') {
            $displayForm
                .= <<<EOF
            <div class = "form-group">
EOF;
            if (!empty($element->getLabel())) {
                $displayForm .= $this->formLabel($element);
            }
            $displayForm .= $this->formElement($element);
            $displayForm .= $this->formElementErrors($element);
            $displayForm .= '</div>';
            break;
        }
        $displayForm .= '&nbsp;';
    endforeach;

    $displayForm .= "<div style=\"border: 10px; vertical-align: top\">$displaySubmitButton</div>";

    $displayForm .= $this->form()->closeTag($this->edititemform);
    $disperrors = '';

    if (isset($this->messages)) {

        foreach ($this->messages as $ekey => $eerrors) {
            $disperror = '';
            foreach ($eerrors as $validator => $verror) {
                $disperror .= "$validator: $verror<br />";
            }
            $disperrors
                .= <<<EOF
        FORM: $ekey : $disperror<br />
EOF;
        }

    }

    if (!empty($disperrors)) {
        $dispe
            = <<<EOF
            <div class="alert alert-danger">$disperrors</div>
EOF;
    }
}

$headerline = <<<EOF
<div class="carheader">Edit Car Details</div>
EOF;

$lform = <<<EOF
<form action="" method="post" enctype="multipart/form-data" class="form-inline">
EOF;

/** @var \Zend\Form\Element $element */
foreach ($this->form->getElements() as $name => $element) :

    switch($element->getAttributes()['type']) {

        case 'submit':
            $element->setAttributes(['class' => 'btn btn-default']);
            $lform .= $this->formElement($element);
            break;

        default:
            $element->setAttributes(['class' => 'form-control']);
            $lform
                .= <<<EOF
            <div class = "form-group">
EOF;
            if (!empty($element->getLabel())) {
                $lform .= $this->formLabel($element);
            }
            $lform .= $this->formElement($element);
            $lform .= $this->formElementErrors($element);
            $lform .= '</div>';
            break;
    }
    $lform .= '&nbsp;';
endforeach;
$lform .= $this->form()->closeTag($this->form);
$photos = $this->photos;
$photo = '';
$itemId = $this->itemid;

foreach ($photos as $url) {

    //TODO: better to pull photoId and provide array to include id and URL
    //or ID as key
    $needle = "$itemId-";
    $photoId = str_replace($needle, '', strstr($url, $needle));

    $photo .=<<<EOF
<div style="position: relative">
<img src="$url">
<div style="position: absolute; bottom: 0">
<button id="rphoto$photoId" type="button" class="btn btn-primary">Remove Photo</button>
</div>
</div>
<br />
EOF;
}

$upStatusMessage = $this->upStatusMessage;

$cont = <<<EOF
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">$headerline $displayForm</div>
        <div class="col-lg-4">$dispe</div>
    </div>
</div>
<br /><br />
<div class="carheader">Photos</div>

$lform
<br /><br />
$photo

$upStatusMessage
EOF;

echo $cont;
?>
<script>
    $( document ).ready(function() {
        $("[id^='rphoto']").click(function() {

            //get photoId
            let photoId = $(this).attr('id').substring(6);

            $.get("/removephoto/itemid/<?=$itemId?>/photoid/" + photoId,  function (data, statusText, xhr) {

            }).always(function(data, textStatus, xhr) {

                console.log("error" + textStatus);
                console.log("STATUS: " + xhr.status);

                if (xhr.status === 200) {
                    console.log('200 Photo Removed.');
                    $("#rphoto" + photoId).text('Photo Removed');
                }
            });
        });
    });
</script>