<h1>Hire Purchase Finance (HP)</h1>
<p>Hire Purchase, commonly referred to as HP, is a form of <a href="<?= $this->serverUrl($this->url('car-finance')) ?>">car finance</a> which can be used to purchase motor vehicles. Around a fifth of car financing is with a HP agreement. It provides an agreement between the buyer and loan provider/seller in which the buyer makes periodic payments over the term of the finance.</p>
<p>The loan is secured against the car which helps lower the cost of the loan. The buyer does not own the car during this period, ownership stays with the seller — only when the last payment is made does ownership transfer to the buyer.</p>
<p>Usually a deposit is made and the rest of the cost of the car is made up with monthly payments.</p>
<p>Dealers or the loan provider may charge initial loan set-up fees in addition. For this reason, when comparing loans, use the APR rate (which includes such fees) as opposed to the headline rate (which won&'t include all the fees) to determine the best deal from different loan providers.</p>
<p>If you have a car to trade in this can be used for a deposit or a discount off the price of the new car — the dealer can then sell the vehicle on or accept it under a <a href="<?= $this->serverUrl($this->url('scrappage-schemes-explained')) ?>">Scrappage Scheme</a>.</p>
<p>Remember also that there is a <strong>14 Day </strong><strong>Cooling Off Period</strong> under the Consumer Credit Act — which allows you 14 days to withdraw from any credit agreement from the day the agreement is concluded. However, the contract to supply the car is still in place with the dealer — so you can withdraw from the credit agreement but you will still need to pay for the car.</p>
<p>Typically deposits are around 10% and APR rates around 5%. As an example, the cost of a loan might be as follows:</p>
<h3>HP Example</h3>
<p>New Car Price £20,000<br />
    Customer Deposit £4,000 + £2,000 dealer contribution<br />
    Loan Arrangement Fees £200<br />
    Total to finance £14,200.00<br />
    5% APR<br />
    36 Monthly Payments at £425.59</p>
<h3><strong>Pros</strong></h3>
<ul>
    <li>Flexible 1—5 yr repayment period</li>
    <li>Relatively low deposit, typically 10%.</li>
    <li>HP agreements come under Voluntary Termination, part of the Consumer Credit Act which allows termination of the contract, along with return of the car, as long as the buyer has paid back at least half the loan amount.</li>
    <li>Can be easier to obtain finance under HP than a standard loan as the car is used as security. If you are able to pay a large deposit you may be able to get a very good APR rate —  even 0%.</li>
    <li>Once the loan is paid off you automatically own the car.</li>
    <li>If you know that you will want to keep the vehicle, the overall cost of HP is cheaper than PCP.</li>
    <li>The buyer can purchase the car outright at any point in time by paying the outstanding loan amount.</li>
</ul>
<h3><strong>Cons</strong></h3>
<ul>
    <li>APR rates can be higher than under PCP.</li>
    <li>You don't own the car —  the lender can take it away if you miss payments.</li>
    <li>The lender can repossess the car without a court order until you've paid 1/3 of the loan amount.</li>
    <li>Lacks flexibility of PCP.</li>
</ul>
<h3>Where to Find HP Finance Deals on New Cars</h3>
<p>HP Finance Providers Car dealers will be only too willing to sign you up to a deal (though they may point you in the direction of PCP rather than HP). Alternatively you can go to specialist finance dealers, e.g</p>
<p><!--<a href="https://www.carfinance247.co.uk" target="_blank" rel="noopener">Car Finance 247</a>--><br />
    <a href="https://www.paidonresults.net/c/49722/1/1819/0">Car Finance Deals</a></p>