<?php
declare(strict_types=1);
$this->headTitle('Home'); ?>
<h1>Scrappage</h1>


<p>
    <span style="font-size: large"><a href="<?=$this->serverUrl($this->url('additem'))?>">Sell your car</a> on scrappage.co.uk <span style="text-decoration: wavy underline">for FREE</span></span>
</p>
<p>Information on <a href="<?=$this->serverUrl($this->url('scrappage-schemes-explained'))?>">2017/2018 Scrappage Schemes</a></p>