<?php
declare(strict_types=1);
$this->headTitle('Scrappage Schemes Explained'); ?>
<h2>Scrappage Schemes Explained</h2>
    <br />
    <br />

<h3>Overview</h3>
Scrappage schemes are deals provided by manufacturers, shops, dealers and/or governments or other public bodies whereby incentives are offered to encourage owners to trade in goods in exchange for something new.

Scrappage schemes gained attention when the UK government in 2009 offered
public subsidy of £1,000 per vehicle, along with an additional manufacturer contribution of £1,000 for car owners to trade in old cars for a new one. This was done to remove older less efficient and more polluting cars off the road and to give a boost to the car market, which was struggling at the time, and to help the wider economy.

Since that time, various companies and manufacturers have offered various trade in and scrappage schemes on a number different types of goods, not just cars. Items include books, video games, jewellery, mobile phones, cameras, boilers, computer equipment, boilers and even kitchens.
<br />
<br />
<br />
    <br />

<h3>2017 Car Scrappage Schemes</h3>
2017 saw the introduction of a number new schemes and trade in deals from car makers in response to growing public concern over pollution caused by diesel powered cars and dieselgate.

The new vehicle scrappage schemes for 2017 are a mixture of scrappage (where your traded in vehicle is scrapped) and trade in where the vehicle may be scrapped or sold on , at the discretion of the dealer.

Some dealers e.g. <a href="<?=$this->serverUrl('/')?>sp/audi-scrappage-scheme-2017">Audi</a> are permanently scrapping all cars traded in under their schemes whereas others like <a href="<?=$this->serverUrl('/')?>sp/bmw">BMW</a> are selling on all vehicles traded in under its scheme.

To qualify generally you will have to be in ownership of the vehicle with it
registered in your name and the trade-in car must usually be around 7 years old or more.

Most dealers will require you to have been in ownership for a time ranging from 90 days to six months, though Kia will allow you to trade-in under there scheme without a qualifying period as long as you have the car registered in your name.

Savings range from £1000 on a Toyota CH-R to £7,500 on an Audi Sportback e-tron.
